require:
  - rubocop-rspec

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'pkg/**/*'

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#'  # Allow long comments
    - '\A\s*it\s'  # Allow long RSpec test descriptions
    - '\A\s*describe\s'  # Allow long RSpec describe blocks
    - '\A\s*context\s'  # Allow long RSpec context blocks

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: empty_lines

Naming/FileName:
  Enabled: true
  Exclude:
    - 'lib/**/*.rb'

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false