# frozen_string_literal: true

source "https://rubygems.org"

# Always use local development paths for raaf gems
gem "raaf-core", path: "../core"
gem "raaf-testing", path: "../testing"
gem "raaf-tracing", path: "../tracing"

# Specify your gem's dependencies in the gemspec
gemspec

group :development do
  gem "rake", "~> 13.0"
  gem "yard", "~> 0.9"
end

group :test do
  gem "rspec", "~> 3.0"
  gem "simplecov", "~> 0.22"
  gem "vcr", "~> 6.1"
  gem "webmock", "~> 3.18"
end

group :development, :test do
  gem "pry", "~> 0.14"
  gem "pry-byebug", "~> 3.10"
  gem "rubocop", "~> 1.21"
  gem "rubocop-rake", "~> 0.6"
  gem "rubocop-rspec", "~> 3.0"
end
