AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'python_env/**/*'  # Exclude Python virtual environment files
    - 'a.rb'  # Temporary file
    - 'haiku_example.rb'  # Temporary example file

Style/Documentation:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  Exclude:
    - 'examples/**/*'  # Examples may use single quotes in interpolations

# Layout/LineLength configured below with additional exclusions

# Reasonable Metrics Configuration
# Disable the most problematic metrics cops that don't add much value
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Keep but relax the useful metrics cops
Metrics/ModuleLength:
  Max: 400  # Allow larger modules

Metrics/BlockLength:
  Max: 60   # Allow longer blocks for complex operations
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'Rakefile'

Metrics/ParameterLists:
  Max: 6    # Allow up to 6 parameters (reasonable for Ruby)
  CountKeywordArgs: false  # Don't count keyword arguments

# Keep block nesting reasonable
Metrics/BlockNesting:
  Max: 5    # Allow one more level for complex nested operations

# Allow reasonable collection sizes
Metrics/CollectionLiteralLength:
  LengthThreshold: 50  # Increased for model lists and command arrays

# Disable some style cops that are overly strict for this codebase
Style/FrozenStringLiteralComment:
  Enabled: false  # Already handled by rubocop-performance

Style/MutableConstant:
  Enabled: false  # Many constants are intentionally mutable

Style/SlicingWithRange:
  Enabled: false  # Allow both [6..-1] and [6..] syntax

Style/SpecialGlobalVars:
  Enabled: false  # Allow $0 for script detection

Style/StringConcatenation:
  Enabled: false  # Allow string concatenation for complex cases

Style/HashLikeCase:
  Enabled: false  # Allow case statements that could be hashes

Style/NumericPredicate:
  Enabled: false  # Allow both > 0 and .positive? syntax

Style/SafeNavigationChainLength:
  Enabled: false  # Allow longer safe navigation chains

# Security exceptions for examples and development code
Security/Eval:
  Exclude:
    - 'examples/**/*'  # Examples may use eval for demonstration

# Lint cops adjustments
Lint/UselessAssignment:
  Exclude:
    - 'examples/**/*'  # Examples may have unused variables for clarity

Lint/UnusedMethodArgument:
  Enabled: false  # Many methods have unused args for interface compatibility

Lint/DuplicateBranch:
  Enabled: false  # Some duplicate branches are intentional for clarity

Lint/MissingSuper:
  Enabled: false  # Some classes intentionally don't call super

Lint/NonLocalExitFromIterator:
  Enabled: false  # Allow returns from iterators when appropriate

# Naming conventions adjustments
Naming/AccessorMethodName:
  Enabled: false  # Allow get_ and set_ prefixes when appropriate

Naming/PredicatePrefix:
  Enabled: false  # Allow has_ prefix for predicate methods

# Layout adjustments
Layout/TrailingWhitespace:
  Exclude:
    - 'examples/**/*'  # Examples may have trailing whitespace
    - 'spec/**/*'      # Test files may have trailing whitespace

Layout/TrailingEmptyLines:
  Exclude:
    - 'spec/**/*'      # Test files may be missing final newlines

# Additional lint cops
Lint/RedundantCopDisableDirective:
  Enabled: false  # Don't flag now-unnecessary rubocop disables

Lint/IneffectiveAccessModifier:
  Enabled: false  # Allow self methods after private declarations

# Method length exceptions for specific complex methods
Metrics/MethodLength:
  Max: 80
  Exclude:
    - 'spec/**/*'
    - 'lib/openai_agents/models/cohere_provider.rb'  # Stream conversion is complex
    - 'lib/openai_agents/tracing/openai_processor.rb'  # Span data creation is complex

# Class length exceptions for complex classes
Metrics/ClassLength:
  Max: 450  # Slightly increased for usage tracking
  Exclude:
    - 'spec/**/*'

# Line length exceptions for specific files with long debug output
Layout/LineLength:
  Max: 120
  Exclude:
    - 'examples/**/*'
    - 'spec/**/*'
    - 'lib/openai_agents/tracing/batch_processor.rb'  # Debug output lines
    - 'lib/openai_agents/agent.rb'  # Tool validation error messages