# Minimal RuboCop configuration for raaf-providers
inherit_from: ~ # Don't inherit from any parent configs

require:
  - rubocop-rspec

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'pkg/**/*'

# Layout rules
Layout/LineLength:
  Max: 120
  Exclude:
    - 'examples/**/*'  # Examples can have longer lines for readability

# Metrics rules - relaxed for provider complexity
Metrics/AbcSize:
  Max: 70  # Providers handle complex API interactions

Metrics/MethodLength:
  Max: 60  # API methods need comprehensive parameter handling
  Exclude:
    - 'lib/raaf/cohere_provider.rb'  # Stream parsing requires complex logic

Metrics/ClassLength:
  Max: 400  # Provider classes are inherently large

Metrics/BlockLength:
  Max: 60
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

Metrics/CyclomaticComplexity:
  Max: 25  # Provider conditionals for different API formats

Metrics/PerceivedComplexity:
  Max: 25

Metrics/ParameterLists:
  Max: 15  # API methods need many optional parameters

Metrics/BlockNesting:
  Max: 4  # Streaming response parsing requires nesting

# Style rules
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashLikeCase:
  Enabled: false  # Provider model selection uses meaningful case statements

# Gemspec rules
Gemspec/DevelopmentDependencies:
  Enabled: false

# Naming rules
Naming/FileName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false  # Provider helper methods don't always follow predicate naming

# Security rules - allow eval in examples
Security/Eval:
  Exclude:
    - 'examples/**/*'

# Lint rules
Lint/UnusedMethodArgument:
  Enabled: false

Lint/MissingSuper:
  Enabled: false  # Provider initialization patterns don't always require super

Lint/DuplicateBranch:
  Enabled: false  # Provider conditionals may have similar branches for different APIs

# Basic RSpec rules only
RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 10

RSpec/DescribeClass:
  Enabled: false

RSpec/FilePath:
  Enabled: false  # Provider specs don't follow deep directory structure

RSpec/SpecFilePathFormat:
  Enabled: false  # Provider specs use flat structure

# Disable problematic cops that cause errors
Capybara/RSpec/PredicateMatcher:
  Enabled: false