plugins:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'pkg/**/*'

# Disable all Metrics cops for the entire gem
Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false


Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/HashLikeCase:
  Enabled: false

Security/Eval:
  Exclude:
    - 'examples/**/*'

Naming/PredicateMethod:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Lint/NestedMethodDefinition:
  Exclude:
    - 'examples/**/*'

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: empty_lines

Naming/FileName:
  Enabled: true
  Exclude:
    - 'lib/**/*.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false
