require:
  - rubocop-rspec

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'pkg/**/*'

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#'  # Allow long comments
    - '\A\s*it\s'  # Allow long RSpec test descriptions
    - '\A\s*describe\s'  # Allow long RSpec describe blocks
    - '\A\s*context\s'  # Allow long RSpec context blocks
    - 'https?://'  # Allow long URLs
    - '\A\s*puts\s'  # Allow long puts statements in examples
  Exclude:
    - 'examples/**/*'

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'examples/**/*'

Metrics/MethodLength:
  Max: 30
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'examples/**/*'

Metrics/CyclomaticComplexity:
  Max: 12
  Exclude:
    - 'examples/**/*'

Metrics/PerceivedComplexity:
  Max: 12
  Exclude:
    - 'examples/**/*'

Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'examples/**/*'

Metrics/ModuleLength:
  Max: 250

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - 'Rakefile'
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/HashLikeCase:
  Enabled: false

Security/Eval:
  Exclude:
    - 'examples/**/*'

Naming/PredicateMethod:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Lint/NestedMethodDefinition:
  Exclude:
    - 'examples/**/*'

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: empty_lines

Naming/FileName:
  Enabled: true
  Exclude:
    - 'lib/**/*.rb'

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 6

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false
