# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in the gemspec
gemspec

group :development do
  gem "rake"
  gem "yard"
end

group :test do
  gem "rspec"
  gem "simplecov"
  gem "vcr"
  gem "webmock"
end

group :development, :test do
  gem "pry"
  gem "pry-byebug"
  gem "rubocop"
  gem "rubocop-rake"
  gem "rubocop-rspec"
end
