# frozen_string_literal: true

source "https://rubygems.org"

# Use local raaf-core gem
gem "raaf-core", path: "../core"

# Specify your gem's dependencies in the gemspec
gemspec

group :development do
  gem "rake", "~> 13.0"
  gem "yard", "~> 0.9"
end

group :test do
  gem "rspec", "~> 3.0"
  gem "simplecov", "~> 0.22"
  gem "webmock", "~> 3.18"
  gem "vcr", "~> 6.1"
end

group :development, :test do
  gem "rubocop", "~> 1.21"
  gem "rubocop-rake", "~> 0.6"
  gem "rubocop-rspec", "~> 2.0"
  gem "pry", "~> 0.14"
  gem "pry-byebug", "~> 3.10"
end
