# DISABLED - Legacy CI workflow replaced by core-ci.yml
# This workflow is disabled in favor of gem-specific workflows
# 
# name: CI
# 
# on:
#   push:
#     branches: [ main, develop ]
#   pull_request:
#     branches: [ main, develop ]
# 
# jobs:
# test:
#   runs-on: ubuntu-latest
#   strategy:
#     matrix:
#       ruby-version: ['3.2', '3.3', '3.4', 'ruby-head']
#       include:
#         - ruby-version: '3.4'
#           experimental: true
#         - ruby-version: 'ruby-head'
#           experimental: true
#     fail-fast: false
# 
#   steps:
#   - uses: actions/checkout@v4
# 
#   - name: Set up Ruby ${{ matrix.ruby-version }}
#     uses: ruby/setup-ruby@v1
#     with:
#       ruby-version: ${{ matrix.ruby-version }}
#       bundler-cache: true
# 
#   - name: Install dependencies (Core gem)
#     run: |
#       cd core
#       bundle install
# 
#   - name: Run tests (Core gem)
#     run: |
#       cd core
#       bundle exec rspec
#     env:
#       OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_TEST }}
#       ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY_TEST }}
#       GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY_TEST }}
# 
#   # Note: Codecov requires a free account setup at codecov.io
#   # Uncomment below if you have configured Codecov for your repository
#   # - name: Upload coverage reports
#   #   uses: codecov/codecov-action@v3
#   #   if: matrix.ruby-version == '3.2'
#   #   with:
#   #     files: ./coverage/coverage.xml
#   #     fail_ci_if_error: false
# 
# lint:
#   runs-on: ubuntu-latest
# 
#   steps:
#   - uses: actions/checkout@v4
# 
#   - name: Set up Ruby
#     uses: ruby/setup-ruby@v1
#     with:
#       ruby-version: '3.2'
#       bundler-cache: true
# 
#   - name: Install dependencies (Core gem)
#     run: |
#       cd core
#       bundle install
# 
#   - name: Run RuboCop (Core gem)
#     run: |
#       cd core
#       bundle exec rubocop
# 
#   - name: Check bundle audit
#     run: |
#       gem install bundler-audit
#       bundle audit check --update
# 
# build:
#   runs-on: ubuntu-latest
# 
#   steps:
#   - uses: actions/checkout@v4
# 
#   - name: Set up Ruby
#     uses: ruby/setup-ruby@v1
#     with:
#       ruby-version: '3.2'
#       bundler-cache: true
# 
#   - name: Install dependencies
#     run: bundle install
# 
#   - name: Build gem
#     run: gem build openai_agents.gemspec
# 
#   # - name: Validate gem
#   #   run: |
#   #     gem install --local openai_agents-*.gem
#   #     ruby -r openai_agents -e "puts 'Gem loads successfully'"
# 
# examples:
#   runs-on: ubuntu-latest
# 
#   steps:
#   - uses: actions/checkout@v4
# 
#   - name: Set up Ruby
#     uses: ruby/setup-ruby@v1
#     with:
#       ruby-version: '3.2'
#       bundler-cache: true
# 
#   - name: Install dependencies
#     run: bundle install
# 
#   - name: Validate examples syntax
#     run: |
#       for file in examples/*.rb; do
#         echo "Checking syntax of $file"
#         ruby -c "$file"
#       done
# 
#   - name: Run basic example
#     run: |
#       cd examples
#       timeout 30s ruby basic_example.rb || echo "Example completed or timed out"
#     env:
#       OPENAI_API_KEY: demo-key-for-testing
#       ANTHROPIC_API_KEY: demo-key-for-testing
#       GEMINI_API_KEY: demo-key-for-testing