name: ⚡ Core Quick Check - Fast Development Feedback

on:
  push:
    branches: [ feature/*, fix/*, hotfix/* ]
    paths: 
      - 'core/**'
      - '.github/workflows/core-quick-check.yml'

# Quick feedback for development branches
env:
  RUBY_VERSION: '3.4.5'
  DEFAULT_RUBY_VERSION: '3.4.5'

jobs:
  # Super fast checks for immediate feedback
  quick-lint:
    name: "⚡ Quick Lint"
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true

    - name: Install dependencies (Core gem)
      run: |
        cd core
        bundle install

    - name: Run RuboCop (Core gem)
      run: |
        cd core
        bundle exec rubocop --parallel

  # Essential unit tests only
  essential-tests:
    name: "🧪 Essential Tests"
    runs-on: ubuntu-latest
    needs: quick-lint
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true

    - name: Install dependencies (Core gem)
      run: |
        cd core
        bundle install

    - name: Run essential unit tests (Core gem)
      run: |
        cd core
        # Run only the most critical unit tests for fast feedback
        bundle exec rspec \
          spec/agent_spec.rb \
          spec/runner_spec.rb \
          spec/models/ \
          --format progress \
          --fail-fast
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_TEST }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY_TEST }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY_TEST }}

  # Smoke test - basic functionality
  smoke-test:
    name: "💨 Smoke Test"
    runs-on: ubuntu-latest
    needs: essential-tests
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true

    - name: Install dependencies (Core gem)
      run: |
        cd core
        bundle install

    - name: Build and test gem loading
      run: |
        cd core
        gem build raaf-core.gemspec
        gem install --local raaf-core-*.gem
        ruby -r raaf-core -e "puts 'Core gem loads successfully'"

    - name: Run basic functionality test
      run: |
        cd core
        ruby -r raaf-core -e "
          agent = RAAF::Agent.new(name: 'Test', instructions: 'Test agent', model: 'gpt-4o')
          puts 'Agent created successfully: ' + agent.name
        "

  # Status check for PR
  quick-check-status:
    name: "✓ Quick Check Status"
    runs-on: ubuntu-latest
    needs: [quick-lint, essential-tests, smoke-test]
    if: always()
    
    steps:
    - name: Check results
      run: |
        echo "## Quick Check Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [[ "${{ needs.quick-lint.result }}" == "success" ]]; then
          echo "✅ Quick Lint: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Quick Lint: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [[ "${{ needs.essential-tests.result }}" == "success" ]]; then
          echo "✅ Essential Tests: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Essential Tests: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [[ "${{ needs.smoke-test.result }}" == "success" ]]; then
          echo "✅ Smoke Test: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Smoke Test: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ needs.quick-lint.result }}" == "success" && "${{ needs.essential-tests.result }}" == "success" && "${{ needs.smoke-test.result }}" == "success" ]]; then
          echo "🎉 All quick checks passed! Ready for full CI." >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Some quick checks failed. Fix these before running full CI." >> $GITHUB_STEP_SUMMARY
        fi

    - name: Fail if quick checks failed
      if: needs.quick-lint.result != 'success' || needs.essential-tests.result != 'success' || needs.smoke-test.result != 'success'
      run: |
        echo "❌ Quick checks failed. See summary above."
        exit 1