# COMMENTED OUT - This workflow is for legacy openai_agents gem structure
# Currently focusing only on core gem development
# 
# name: Release
# 
# on:
#   push:
#     tags:
#       - 'v*'
# 
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         ruby-version: ['3.2', '3.3', '3.4', 'ruby-head']
#         include:
#           - ruby-version: '3.4'
#             experimental: true
#           - ruby-version: 'ruby-head'
#             experimental: true
#       fail-fast: false
# 
#     steps:
#     - uses: actions/checkout@v4
# 
#     - name: Set up Ruby ${{ matrix.ruby-version }}
#       uses: ruby/setup-ruby@v1
#       with:
#         ruby-version: ${{ matrix.ruby-version }}
#         bundler-cache: true
# 
#     - name: Install dependencies
#       run: bundle install
# 
#     - name: Run tests
#       run: bundle exec rspec
#       env:
#         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_TEST }}
#         ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY_TEST }}
#         GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY_TEST }}
# 
#     - name: Run RuboCop
#       run: bundle exec rubocop
# 
#   build-and-publish:
#     needs: test
#     runs-on: ubuntu-latest
# 
#     steps:
#     - uses: actions/checkout@v4
# 
#     - name: Set up Ruby
#       uses: ruby/setup-ruby@v1
#       with:
#         ruby-version: '3.2'
#         bundler-cache: true
# 
#     - name: Install dependencies
#       run: bundle install
# 
#     - name: Build gem
#       run: gem build openai_agents.gemspec
# 
#     # - name: Validate gem
#     #   run: |
#     #     gem install --local openai_agents-*.gem
#     #     ruby -r openai_agents -e "puts 'Gem loads successfully'"
# 
#     - name: Create GitHub Release
#       uses: softprops/action-gh-release@v1
#       with:
#         files: |
#           openai_agents-*.gem
#         body: |
#           ## What's Changed
#           
#           See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for detailed changes.
#           
#           ## Installation
#           
#           ```bash
#           gem install openai_agents -v ${{ github.ref_name }}
#           ```
#           
#           Or add to your Gemfile:
#           
#           ```ruby
#           gem 'openai_agents', '~> ${{ github.ref_name }}'
#           ```
#           
#           🤖 Generated with [Claude Code](https://claude.ai/code)
#         draft: false
#         prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# 
# 
#     # - name: Update documentation
#     #   run: |
#     #     # Generate and push documentation
#     #     bundle exec yard doc
#     #     if [ -d "doc" ]; then
#     #       echo "Documentation generated successfully"
#     #     fi
# 
#   notify:
#     needs: [test, build-and-publish]
#     runs-on: ubuntu-latest
#     if: always()
# 
#     steps:
#     - name: Notify on success
#       if: needs.build-and-publish.result == 'success'
#       run: |
#         echo "✅ Release ${{ github.ref_name }} published successfully!"
#         echo "🔗 GitHub Release: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
# 
#     - name: Notify on failure
#       if: needs.build-and-publish.result == 'failure' || needs.test.result == 'failure'
#       run: |
#         echo "❌ Release ${{ github.ref_name }} failed!"
#         echo "Please check the workflow logs for details."